package org.cesiumjs.cesium;

public enum ScreenSpaceEventType {
  LEFT_DOWN,
  LEFT_UP,
  LEFT_CLICK,
  LEFT_DOUBLE_CLICK,
  RIGHT_DOWN,
  RIGHT_UP,
  RIGHT_CLICK,
  RIGHT_DOUBLE_CLICK,
  MIDDLE_DOWN,
  MIDDLE_UP,
  MIDDLE_CLICK,
  MIDDLE_DOUBLE_CLICK,
  MOUSE_MOVE,
  WHEEL,
  PINCH_START,
  PINCH_END,
  PINCH_MOVE
}
